name: build
on:
  pull_request:
    paths-ignore:
      - 'design/*'
      - 'NOTICE'
      - 'README'
  push:
    paths-ignore:
      - 'design/*'
      - 'NOTICE'
      - 'README'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Get the short SHA of the current commit
        id: commit-info
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
      - name: Prepare the artifact folder
        run: mkdir build
      - name: Build the project (PIC18F4550_NISSE)
        uses: jeandeaual/mplabx-xc8-build-action@v0.1.0
        with:
          project: firmware/third_party/mla_v2013_12_20/apps/usb/device/hid_keyboard/firmware/MPLAB.X
          configuration: PIC18F4550_NISSE
      - name: Prepare the firmware file (PIC18F4550_NISSE)
        run: sudo mv firmware/third_party/mla_v2013_12_20/apps/usb/device/hid_keyboard/firmware/MPLAB.X/dist/PIC18F4550_NISSE/production/MPLAB.X.production.hex build/esrille.nisse.pic18f4550.hex
      - name: Build the project (PIC18F4550_NISSE_TSAP)
        uses: jeandeaual/mplabx-xc8-build-action@v0.1.0
        with:
          project: firmware/third_party/mla_v2013_12_20/apps/usb/device/hid_keyboard/firmware/MPLAB.X
          configuration: PIC18F4550_NISSE_TSAP
      - name: Prepare the firmware file (PIC18F4550_NISSE_TSAP)
        run: sudo mv firmware/third_party/mla_v2013_12_20/apps/usb/device/hid_keyboard/firmware/MPLAB.X/dist/PIC18F4550_NISSE_TSAP/production/MPLAB.X.production.hex build/esrille.nisse.pic18f4550.tsap.hex
      - name: Build the project (PIC18F47J53_NISSE_USB)
        uses: jeandeaual/mplabx-xc8-build-action@v0.1.0
        with:
          project: firmware/third_party/mla_v2013_12_20/apps/usb/device/hid_keyboard/firmware/MPLAB.X
          configuration: PIC18F47J53_NISSE_USB
      - name: Prepare the firmware file (PIC18F47J53_NISSE_USB)
        run: sudo mv firmware/third_party/mla_v2013_12_20/apps/usb/device/hid_keyboard/firmware/MPLAB.X/dist/PIC18F47J53_NISSE_USB/production/MPLAB.X.production.hex build/esrille.nisse.pic18f47j53.hex
      - name: Build the project (PIC18F47J53_NISSE_USB_TSAP)
        uses: jeandeaual/mplabx-xc8-build-action@v0.1.0
        with:
          project: firmware/third_party/mla_v2013_12_20/apps/usb/device/hid_keyboard/firmware/MPLAB.X
          configuration: PIC18F47J53_NISSE_USB_TSAP
      - name: Prepare the firmware file (PIC18F47J53_NISSE_USB_TSAP)
        run: sudo mv firmware/third_party/mla_v2013_12_20/apps/usb/device/hid_keyboard/firmware/MPLAB.X/dist/PIC18F47J53_NISSE_USB_TSAP/production/MPLAB.X.production.hex build/esrille.nisse.pic18f47j53.tsap.hex
      - name: Build the project (PIC18F47J53_NISSE_BLE)
        uses: jeandeaual/mplabx-xc8-build-action@v0.1.0
        with:
          project: firmware/third_party/mla_v2013_12_20/apps/usb/device/hid_keyboard/firmware/MPLAB.X
          configuration: PIC18F47J53_NISSE_BLE
      - name: Prepare the firmware file (PIC18F47J53_NISSE_BLE)
        run: sudo mv firmware/third_party/mla_v2013_12_20/apps/usb/device/hid_keyboard/firmware/MPLAB.X/dist/PIC18F47J53_NISSE_BLE/production/MPLAB.X.production.hex build/esrille.nisse.pic18f47j53.ble.hex
      - name: Build the project (PIC18F47J53_NISSE_BLE_TSAP)
        uses: jeandeaual/mplabx-xc8-build-action@v0.1.0
        with:
          project: firmware/third_party/mla_v2013_12_20/apps/usb/device/hid_keyboard/firmware/MPLAB.X
          configuration: PIC18F47J53_NISSE_BLE_TSAP
      - name: Prepare the firmware file (PIC18F47J53_NISSE_BLE_TSAP)
        run: sudo mv firmware/third_party/mla_v2013_12_20/apps/usb/device/hid_keyboard/firmware/MPLAB.X/dist/PIC18F47J53_NISSE_BLE_TSAP/production/MPLAB.X.production.hex build/esrille.nisse.pic18f47j53.ble.tsap.hex
      - name: Upload the firmwares
        uses: actions/upload-artifact@v2.2.3
        with:
          name: esrille.nisse.${{ steps.commit-info.outputs.sha7 }}
          path: build
  release:
    # Only release when pushing a tag
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Get the short SHA of the current commit
        id: commit-info
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
      - name: Download the built firmwares
        uses: actions/download-artifact@v2
        with:
          name: esrille.nisse.${{ steps.commit-info.outputs.sha7 }}
          path: build
      - name: Create a new release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/*.hex
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
